---
title: Improving the experience
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@improvingtheexperience.com
description: Carefully curated collections of lessons in improving experiences from
  leaders in our industry.
baseurl: 
url: http://improvingtheexperience.com
twitter_username: imprvtx
github_username: improvingtheexperience
markdown: kramdown
