---
title: Improving The Experience
timezone: UTC
collections:
  posts:
    title: Insights
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    article:
      title:
      intro-text:
      image:
      url:
    layout: post
email: hello@improvingtheexperience.com
description: Carefully curated insights in improving web experiences by leaders in
  our industry
baseurl:
url: http://improvingtheexperience.com
twitter_username: mprvtx
markdown: kramdown
